name: Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: vladimirkutuev/cmocka:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and test source code
        run: |
         ./script/build.sh &&\
         ./script/test.sh

